#!/usr/bin/env bash
# Install and configure HAProxy for load balancing

# Install HAProxy if not already installed
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo "
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart
