#!/usr/bin/env bash
# ssh_config

# Configure ssh client to use public key authentication and other settings

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    User ubuntu
